[manga]
title = "看漫画"
url = "https://www.manhuagui.com/list/update.html"
entrySelector = "div.book-list"
titleSelector = "ul#contList > li:first-child span.updateon"
linkSelector = "ul#contList > li:first-child a.bcover"
contentSelector = "ul#contList"

[movie]
title = "电影日历"
url = "https://www.cikeee.cc/"
entrySelector = "div#main-wrap"
titleSelector = ["span#month", "span#day", "span#week", "div#daytext"]
linkSelector = "a#movie-img-a"
contentSelector = "div#movie-wrap"

[cfa]
title = "CFA Institute Research"
url = "https://rpc.cfainstitute.org/"
entrySelector = "section.grid__item--initial a.brand-card.flex__item"
titleSelector = "h4"
linkSelector = "*"
filters = ["Financial Analysts Journal"]

[github]
title = "Github Trending Daily"
url = "https://github.com/trending"
entrySelector = "div.Box"
titleSelector = "article:first-child h2"
linkSelector = "nav a:first-child"
contentSelector = "div:nth-child(2)"