[manga]
title = "看漫画"
url = "https://www.manhuagui.com/list/update.html"
entrySelector = "div.book-list"
titleSelector = "ul#contList > li:first-child span.updateon"
linkSelector = "ul#contList > li:first-child a.bcover"
contentSelector = "ul#contList"

[cfa]
title = "CFA Institute Research"
url = "https://rpc.cfainstitute.org/"
entrySelector = "section.grid__item--initial a.brand-card.flex__item"
titleSelector = "h4"
linkSelector = "*"
filters = ["Financial Analysts Journal"]