[manga]
title = "看漫画"
url = "https://www.manhuagui.com/list/update.html"
entrySelector = "ul#contList > li"
titleSelector = "p.ell"
linkSelector = "p.ell > a"

[movie]
title = "电影日历"
url = "https://www.cikeee.cc/"
entrySelector = "div#main-wrap"
titleSelector = ["span#month", "span#day", "span#week", "div#daytext"]
linkSelector = "a#movie-img-a"
contentSelector = "div#movie-wrap"


