[manga]
title = "看漫画"
url = "https://www.manhuagui.com/list/japan/update.html"
entrySelector = "ul#contList > li"
titleSelector = "p.ell"
linkSelector = "p.ell > a"

[article]
title = "每日一文"
url = "https://www.qhsou.com/one/"
entrySelector = "div.container"
titleSelector = "h3"
