[manga]
title = "看漫画 - 日本漫画"
url = "https://www.manhuagui.com/list/japan_lianzai/update.html"
entrySelector = "ul#contList > li"
titleSelector = "p.ell"
linkSelector = "p.ell > a"

[cfa]
title = "CFA Institute Daily Browse"
url = "https://blogs.cfainstitute.org/"
entrySelector = "div.post-item"
titleSelector = "a.post-title"
linkSelector = "a.post-title"
contentSelector = ["div.small-12.medium-5.columns", "p"]

[ai]
title = "Informed AI News"
url = "https://informedainews.com/news"
entrySelector = "article.overflow-hidden"
titleSelector = "h3"
linkSelector = "a"
contentSelector = ["p", "div.text-sm"]
