name: Publish RSS feeds to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run the action every 8 hours
    - cron:  '0 */8 * * *'
  workflow_dispatch:

env:
  CI: true
jobs:
  publish-feeds:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: microsoft/playwright-github-action@v1
    - run: npx playwright install firefox
    # GitHub Actions unfortunately does not support retries;
    # this is a cumbersome method of retrying twice in case of errors:
    - run: npx feed-me-up-scotty || npx feed-me-up-scotty || npx feed-me-up-scotty
    - name: Deploy to GitHub Pages
      run: |
        git config user.name $GITHUB_ACTOR
        git config user.email $GITHUB_ACTOR@users.noreply.github.com
        git remote add gh-pages-remote https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git fetch --no-recurse-submodules
        git worktree add ./gh-pages gh-pages
        cd gh-pages
        git rm -r .
        cp -r ../public/. .
        sed -i -e 's#//cf.mhgui.com#https://cf.mhgui.com#g' -e 's/data-src/src/g' -e 's/<p class="ell">.*<\/p>//g' -e 's/<span class="bg"><\/span>//g' -e 's/<span class="sl"><\/span>//g' -e 's/span/div/g' -e 's/<em>\(.*\)<\/em>/<p>评分： <b>\1<\/b><\/p>/g' -e 's/<a[^>]*>//g;s/<\/a>//g' ./manga.xml
        sed -i -e 's#/uploads#https://www.cikeee.cc/uploads#g' -e '/<div id="movie-img-fixed">.*<\/div>/d' -e 's/span/blockquote/g' -e 's/<a/<div/g' -e 's/a>/div>/g' -e 's/target.*"//g' -e 's/href.*"//g' ./movie.xml
        git add .
        git commit --message="Deploying to GitHub Pages from $GITHUB_SHA"
        git push gh-pages-remote gh-pages:gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
